spring.application.name=BillingSoftware

# === Database Configuration ===
spring.datasource.url=jdbc:postgresql://dpg-d20hqc3e5dus73decaog-a:5432/billingsoftware
spring.datasource.username=billingsoftware_user
spring.datasource.password=9siGXliabgXqQGqdbUF1xtwOLjPuP0bK
spring.datasource.driver-class-name=org.postgresql.Driver

# === Hibernate / JPA Configuration ===
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true              
spring.jpa.properties.hibernate.format_sql=true
	
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

